- name: Copy MongoDB repo file
  copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/

- name: Install MongoDB
  yum:
    name: mongodb-org
    state: present

- name: Update MongoDB config file from listening 127.0.0.1 to 0.0.0.0
  ansible.builtin.replace:
    path: /etc/mongodb.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
