- name: install Nginx
  ansible.builtin.yum:
    name: nginx
    state: present

- name: Download {{ APP }} component
  include_role:
    name: common
    tasks_from: curl_download
  vars:
    URL: "https://github.com/roboshop-devops-project/frontend/archive/main.zip"
    EXTRACT_DIR: /usr/share/nginx/html
    APP_USER: root

- name: move zipped file
  ansible_builtin.shell: mv frontend-main/* .
  when: COMPONENT == "frontend"

- name: move zipped file
  ansible_builtin.shell: mv static/* .
  when: COMPONENT == "frontend"



- name: Copy Nginx Config file
  template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Start nginx service
  systemd:
    name: nginx
    state: restarted