- name: Download {{ APP }} component
  get_url:
    url: "{{URL}}"
    dest: /tmp/{{APP}}.zip

- name: Remove old content
  ansible.builtin.file:
    path: "{{EXTRACT_DIR}}"
    state: absent

- name: Create directory for {{ APP }} component
  ansible.builtin.file:
    path: "{{EXTRACT_DIR}}"
    state: directory
  become_user: "{{APP_USER}}"

- name: Unarchive {{ APP }} component
  ansible.builtin.unarchive:
    src: /tmp/{{APP}}.zip
    dest: "{{EXTRACT_DIR}}"
    remote_src: yes
  become_user: "{{APP_USER}}"

- name:  Move Htdocs directory
  shell: mv /usr/share/nginx/html/static/* /usr/share/nginx/html/.
  when: APP == "frontend"
#go with move command above instead of below two syntaxes below

#- name: Move Htdocs directory
#  ansible.builtin.copy:
#    dest: /usr/share/nginx/html/.
#   remote_src: yes
#  when: APP == "frontend"

#- name: Remove old htdocs
#  ansible.builtin.file:
#    path: /usr/share/nginx/html/static
#    state: absent
#  when: APP == "frontend"





