- name: Install NodeJS
  yum:
    name:
      - nodejs
      - make
      - gcc-c++
    state: present

- name: Download {{ APP }} component
  include_role:
    name: common
    tasks_from: curl_download
  vars:
    URL: "https://dev.azure.com/DevOps-Batches/f635c088-1047-40e8-8c29-2e3b05a38010/_apis/git/repositories/f62a488c-687f-4caf-9e5e-e751cf9b1603/items?path=%2F&versionDescriptor%5BversionOptions%5D=0&versionDescriptor%5BversionType%5D=0&versionDescriptor%5Bversion%5D=master&resolveLfs=true&%24format=zip&api-version=5.0&download=true"
    EXTRACT_DIR: /home/roboshop/cart
    APP_USER: roboshop

- name: Install NodeJS Module
  community.general.npm:
    path: /home/roboshop/cart
  become_user: roboshop

- name: Update systemd script for cart service
  ansible.builtin.replace:
    path: /home/roboshop/cart/systemd.service
    regexp: 'MONGO_DNSNAME'
    replace: 'mongodb.shaik.cf'

- name: Setup systemd script
  shell: mv /home/roboshop/cart/systemd.service /etc/systemd/system/cart.service

- name: Start cart service
  systemd:
    name: cart
    state: restarted
    enabled: yes
    daemon_reload: yes



